### ISSUE TITLE
Found a bug

### ISSUE THREAD

**Issue by staoran** [AsakusaRinne/HuggingfaceHub#1]
https://github.com/AsakusaRinne/HuggingfaceHub/blob/1f7373c6fbc6df2adc431d6aa4cdd2f8d7440109/HuggingfaceHub/HFDownloader.DownloadFile.cs#L490-L492
Based on the following code, this should be
```filename= $"{subfolder}/{filename}"; ```

**Comment by SanftMonster** [comment]
That's a good catch! Would you like to make a PR for it?
